<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="CONTENT-TYPE" content="text/html; charset=UTF-8">
  <link rel="stylesheet" href="styles/style.css"/>
  <title>Gax , dateresa</title>
</head>
<body>
  <nav>
        <a href="index.html" >
    Home</a>
         <a href="index.html" > projects</a>
         <a href="index.html" > contacto</a>
         </div>
  </ul>
  <nav>
    <head>
      <div class="center">
      </div>
        <img alin-center;
      <img src=""></p>
    <img src="./IMG_16730714148887306.jpg" width="103" height="130">
    <a>
        <h6>
       Ã‰le Ã© um jovem de respeitoğŸ˜‡
       Gosta de trabalhar ğŸ“±
       Estudante da 12Â°classğŸ“
        e obrigatÃ³rio ğŸ’•ğŸ’•ğŸ’–ğŸ’–
        </h6>
    </a>
     <h2 style="#47ff40
      margin: 7 auto;
      width:100;
      height:100;
      text-alin:center;"
<p style="padding:25px;border:1px solid #ff152a;">Gax dateresa</p></h2>
      
  <h2> <a> <p style="color:green;"> criador de sites</p> </a> </h2>
    </head>
  <main>
    <section>
   
 <h3>sobre mim </h3>
 
<p style="color:whit;"> <body>sou</body> Gax dateresa sou um jovem de 18 anos de idade 
        com muito esforÃ§o tentando quen fim consegue o que eu
        desejava ser um cara que fas sites e vende bem barato
        eu sou onfam de mÃ£e e pai morando em MoÃ§ambique provinÃ§ia da ZambÃ©zia.
        mÃ²ro com meus tius .pra eles ta tudo bem prame normalmente 
        sou estudante 12Â°classe .nÃ£o tenho condiÃ§Ãµes favoraveis para os 
        meus estudos mas mesmo assim continuarei a minha batalha .os meus encaregado 
        estÃ£o sofrendo.
      </p>
    </section>
    </main>
  <footer>
    <a>
      
      <h7 style="background-color:#0000ff;
      margin: 100 auto;
      width:190;
      height:150;
      text-alin:center;">facebook</h7>
    </a>
  
<a href="gaxdateresa3@gmail.net">https://www.facebook.com/gax.dateresa >
